title: hello world python program
description: how to create hello world python program
template:
  repo: hello-world-python-program-template
  name: hello-world-python-program
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
